name: Android CI

on:
  push:
    branches: [ "dev" ]

jobs:
  setupAndroid:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code to dev branch
        uses: actions/checkout@v2
          
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew

  buildAPK:
    needs: [ setupAndroid ]
    name: Generate APK debug
    runs-on: ubuntu-latest

    steps:
      - name: Generate apk debug
        run: ./gradlew app:assembleDebug --stacktrace
        
  #STEP 2 : Upload the Artifact
  upload:
    needs: [ setupAndroid, buildAPK ]
    name: Upload the apk to artifact
    runs-on: ubuntu-latest

    steps:
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
